aasm_pnds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('summernote/', include('django_summernote.urls')),
    path('', include('main.urls')),
    path('custom/', include('custom.urls')),
    path('users/', include('users.urls')),
    path('funsionariu/', include('funsionariu.urls')),
    path('ukl/', include('ukl.urls')),
    path('notification/', include('notification.urls')),
    path('api/notification/', include('notification.api.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "PNDS - UKL MONITORING SYSTEM - SUPER USER"
admin.site.site_title = "PNDS - UKL MONITORING SYSTEM - SUPER USER"
admin.site.index_title = "Portal Super User"

ukl/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dash/', views.UKLDash, name="ukl-dash"),
    
    # survey
    path('survey/add', views.AddSurveyUKL, name="AddSurveyUKL"),
    path('survey/update/<str:hashid>', views.UpdateSurveyUKL, name="UpdateSurveyUKL"),
    path('survey/detail/<str:hashid>', views.DetailSurveyUKL, name="DetailSurveyUKL"),
    path('survey/sent/<str:hashid>', views.SentSurvey, name="SentSurvey"),
    # survey image
    path('survey/image/upload/<str:hashid>', views.AddSurveyImage, name="AddSurveyImage"),
    path('survey/image/update/<str:hashid>', views.UpdateSurveyImage, name="UpdateSurveyImage"),
    path('survey/image/delete/<str:hashid>', views.DeleteSurveyImage, name="DeleteSurveyImage"),

    # survey benefisiariu
    path('survey/benefisiariu/add/<str:hashid>', views.AddBenefisiariu, name="AddBenefisiariu"),
    path('survey/benefisiariu/update/<str:hashid>', views.UpdateBenefisiariu, name="UpdateBenefisiariu"),
    path('survey/benefisiariu/upload/doc/<str:hashid>', views.UploadBenefisiariuDoc, name="UploadBenefisiariuDoc"),
    path('survey/benefisiariu/update/doc/<str:hashid>', views.UpdateBenefisiariuDoc, name="UpdateBenefisiariuDoc"),
    path('survey/benefisiariu/delete/doc/<str:hashid>', views.DeleteBenefisiariuDoc, name="DeleteBenefisiariuDoc"),

    # atualiza info implementasaun
    path('implementation/benefisiariu/info/update/<str:hashid>', views.FPAtualizaInfoImple, name="FPAtualizaInfoImple"),
    path('implementation/benefisiariu/doc/add/<str:hashid>', views.AddImplementationImage, name="AddImplementationImage"),
    path('implementation/benefisiariu/doc/update/<str:hashid>', views.UpdateImplementationImage, name="UpdateImplementationImage"),
    path('implementation/benefisiariu/doc/delete/<str:hashid>', views.deleteImplementationImage, name="deleteImplementationImage"),
    path('implementation/benefisiariu/implementation/info/sent/<str:hashid>', views.SentImplementation, name="SentImplementation"),

    # implementation benefisiariu
    path('implementation/add', views.AddImplementationUKL, name="AddImplementationUKL"),

    # loading
    path('load/benefisiariu/detail', views.ajax_load_detail_benefisiariu, name="ajax_load_detail_benefisiariu"),

    # dir munisipiu
    path('dir/mun/dash/', views.UKLDMDash, name="dirmun-ukl-dash"),
    path('dir/mun/implementation/benefisiariu/<str:hashid>', views.DMUKLImplementBenef, name="implementa-ukl-benef"),
    path('dir/mun/implementation/benefisiariu/detail/<str:hashid>', views.DMUKLImplementBenefDetail, name="DMUKLImplementBenefDetail"),


]

ukl/models.py
from django.db import models
import datetime
from django.core.validators import FileExtensionValidator
from custom.models import *
from custom.utils import *
from funsionariu.models import *
from django.contrib.auth.models import User
# Create your models here.

class SurveyUKL(models.Model):
	village = models.ForeignKey(Village, on_delete=models.CASCADE,null=True,verbose_name="Survey iha Suku ne'ebe?")
	administrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True,verbose_name="Survey iha Postu ne'ebe?")
	municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True,verbose_name="Survey iha Munisipiu ne'ebe?")
	aldeia = models.ForeignKey(Aldeia, on_delete=models.CASCADE,null=True,verbose_name="Survey iha Aldeia ne'ebe?")
	surveyDate = models.DateField(null=True,verbose_name="Data Survey")
	description = models.TextField(null=True,blank=True,verbose_name="Informasaun Adisional")
	
	is_locked = models.BooleanField(default=False, null=True, blank=True)
	is_sent = models.BooleanField(default=False, null=True, blank=True)
	is_approved = models.BooleanField(default=False, null=True, blank=True)
	is_rejected = models.BooleanField(default=False, null=True, blank=True)
	is_implemented = models.BooleanField(default=False, null=True, blank=True)
	rejected_info = models.TextField(null=True,blank=True)
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

class SurveyUKLImage(models.Model):
	survey = models.ForeignKey(SurveyUKL, on_delete=models.CASCADE,null=True,verbose_name="Dadus Survey")
	image = models.ImageField(upload_to='Survey_UKL_Image', null=True,blank=True,verbose_name="Upload Imajen Survey")

	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def __str__(self):
		template = 'Survey : {0.survey}'
		return template.format(self)

class BenefisiariuUKL(models.Model):
	survey = models.ForeignKey(SurveyUKL, on_delete=models.CASCADE,null=True,verbose_name="Dadus Survey")
	naran = models.CharField(max_length=200, null=True)
	seksu = models.CharField(choices=[('Mane','Mane'),('Feto','Feto')],max_length=10,null=True,blank=True)
	aldeia = models.ForeignKey(Aldeia, on_delete=models.CASCADE,null=True,blank=True)
	village = models.ForeignKey(Village, on_delete=models.CASCADE,null=True,related_name="benefitVillage")
	administrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True,related_name="benefitAdministrativePost")
	municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True,related_name="benefitMunicipality")
	nu_telefone = models.CharField(max_length=200, null=True)
	eleitoral = models.IntegerField(unique=True,null=True,verbose_name="Nu. Kartaun Eleitoral")
	image = models.ImageField(upload_to='Benefisiariu_Image', null=True,blank=True,verbose_name="Upload Fotografia Benefisiariu (Ex: .PNG or JPG)")

	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def benefitDocs(self):
		return BenefisiariuDoc.objects.filter(benefisiariu=self)

	def __str__(self):
		template = ' Benefisiariu : {0.naran}'
		return template.format(self)

class BenefisiariuDoc(models.Model):
	benefisiariu = models.ForeignKey(BenefisiariuUKL,on_delete=models.CASCADE,null=True,related_name="benefitdoc")
	name = models.CharField(max_length=200, null=True)
	image = models.FileField(upload_to=upload_doc_benefit, null=True, blank=True,
			validators=[FileExtensionValidator(allowed_extensions=['jpg','png'])], verbose_name="Upload Dokumentu")
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def __str__(self):
		template = 'Benefisiariu : {0.benefisiariu.naran} '
		return template.format(self)	


class ImplementasaunUKL(models.Model):
	year = models.ForeignKey(AnoFiscal,on_delete=models.SET_NULL,null=True,blank=True,related_name="implementationyear",verbose_name="Ano Fiskal")
	survey = models.ForeignKey(SurveyUKL,on_delete=models.SET_NULL,null=True,blank=True,related_name="implementationsurvey")
	benefisiariu = models.OneToOneField(BenefisiariuUKL,on_delete=models.CASCADE,null=True,related_name="implementationbenefit")
	aldeia = models.ForeignKey(Aldeia, on_delete=models.CASCADE,null=True,blank=True)
	village = models.ForeignKey(Village, on_delete=models.CASCADE,null=True)
	administrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True)
	municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True)
	startdate = models.DateField(null=True)
	enddate = models.DateField(null=True)
	budget = models.DecimalField(default=0,decimal_places=2,max_digits=10,verbose_name="Orsamentu Projetu",null=True)
	distancemun = models.CharField(max_length=200, null=True,blank=True,verbose_name="Distansia husi Munisipiu")
	implementby = models.CharField(max_length=200, null=True,blank=True,verbose_name="Implementa husi")
	medida = models.CharField(max_length=200, null=True,blank=True,verbose_name="Medida Uma")
	statusImplementasaun = models.CharField(choices=[('Not Start','Not Start'),('On Going','On Going'),('Pending','Pending'),('Abandone','Abandone'),('Complate','Complate')],default="Not Start",max_length=30,null=True,blank=True,verbose_name="Status")
	
	is_locked = models.BooleanField(default=False, null=True, blank=True)
	is_sent = models.BooleanField(default=False, null=True, blank=True)
	is_approved = models.BooleanField(default=False, null=True, blank=True)
	is_rejected = models.BooleanField(default=False, null=True, blank=True)
	rejected_info = models.TextField(null=True,blank=True)
	description = models.TextField(null=True,blank=True)
	
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def __str__(self):
		template = '{0.benefisiariu} {0.village}'
		return template.format(self)

class ImplementasaunUKLImage(models.Model):
	implementasaun = models.ForeignKey(ImplementasaunUKL, on_delete=models.CASCADE,null=True,verbose_name="Dadus Implementasaun UKL")
	image = models.ImageField(upload_to='Implementasaun_UKL', null=True,blank=True,verbose_name="Upload Imajen Implementasaun")

	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def __str__(self):
		template = 'implementasaun : {0.implementasaun}'
		return template.format(self)

class ImplementasaunPoint(models.Model):
	survey = models.OneToOneField(SurveyUKL, on_delete=models.CASCADE, null=True,related_name="surveyLocation")
	latitude = models.CharField(max_length=20, null=True, blank=True)
	longitude = models.CharField(max_length=20, null=True, blank=True)
	image = models.ImageField(upload_to='implementationLocation', null=True,blank=True)

	def __str__(self):
		template = '{0.survey}'
		return template.format(self)

class ImplementationMonitoringUKL(models.Model):
	funsionariu = models.ForeignKey(Funsionariu, null=True, on_delete= models.SET_NULL)
	implementasaun = models.ForeignKey('ImplementasaunUKL', null=True, on_delete= models.CASCADE,related_name="implementasaun")
	pursentu_programa =models.DecimalField(decimal_places=2,max_digits=10,verbose_name="Pursentu Implementasaun",null=True)
	pursentu_acumulativa =models.DecimalField(decimal_places=2,max_digits=10,verbose_name="Pursentu Acumulativa",null=True)
	orsamentu_gastu = models.DecimalField(decimal_places=2,max_digits=10,verbose_name="Orsamentu Gastus",null=True,blank=True)
	orsamentu_acumulativa = models.DecimalField(decimal_places=2,max_digits=10,verbose_name="Orsamentu Acumulativa",null=True,blank=True)
	komentariu = models.TextField(null=True, blank=True)
	monitoring_date = models.DateField(auto_now_add=False)

	is_locked = models.BooleanField(default=False, null=True, blank=True)
	is_sent = models.BooleanField(default=False, null=True, blank=True)
	is_approved = models.BooleanField(default=False, null=True, blank=True)
	is_rejected = models.BooleanField(default=False, null=True, blank=True)
	rejected_info = models.TextField(null=True,blank=True)

	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def __str__(self):
		template = '{0.implementasaun}'
		return template.format(self)

class ImplementationMonitoringUKLImage(models.Model):
	monitoring = models.ForeignKey(ImplementationMonitoringUKL, on_delete=models.CASCADE,null=True,verbose_name="Dadus Monitoring Implementasaun UKL")
	image = models.ImageField(upload_to='ImplementationMonitoringUKL', null=True,blank=True,verbose_name="Upload Imajen Monitoring Implementasaun")

	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)

	def __str__(self):
		template = 'monitoring : {0.monitoring}'
		return template.format(self)

ukl/views.py
from django.shortcuts import render

# Create your views here.

ukl/views/dm_ukl_m.py
from django.shortcuts import render,redirect, get_object_or_404,HttpResponse
from django.contrib import messages
from funsionariu.models import Funsionariu,UserFunsionariu
from ukl.models import *
from ukl.forms import *
from ukl.utils import c_user_fun
from django.contrib.auth.models import User,Group
from custom.utils import *
from custom.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from users.decorators import allowed_users

@login_required
@allowed_users(allowed_roles=['dir_mun'])
def DMUKLImplementBenef(request,hashid):
	group = request.user.groups.all()[0].name
	benefisiariu = get_object_or_404(BenefisiariuUKL,hashed=hashid)
	survey = get_object_or_404(SurveyUKL,hashed=benefisiariu.survey.hashed)
	if request.method == "POST":
		_, newid = getlastid(ImplementasaunUKL)
		hashid = hash_md5(str(newid))
		form = ImplementasaunUKLForm1(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.hashed = hashid
			instance.benefisiariu = benefisiariu
			instance.survey = survey
			mun = get_object_or_404(Municipality,id=survey.municipality.id)
			post = get_object_or_404(AdministrativePost,id=survey.administrativepost.id)
			vill = get_object_or_404(Village,id=survey.village.id)
			ald = get_object_or_404(Aldeia,id=survey.aldeia.id)
			instance.municipality = mun
			instance.administrativepost = post
			instance.village = vill
			instance.aldeia = ald
			instance.user_created = request.user
			instance.save()
			messages.success(request, f'Implementasaun Programa UKL ba benefisiariu {benefisiariu.naran} Rejistu ho Susesu.')
			return redirect('notifDetailSurveyUKL',benefisiariu.survey.hashed)
	else:	
		form = ImplementasaunUKLForm1()

	context ={
		"title":f"Formulariu Implementasaun Programa UKL, Benefisiariu {benefisiariu.naran}",
		"page":"dmimpleform",
		"form":form,"group":group,"benefisiariu":benefisiariu,
		"active_programa":"active",
	}
	return render(request,'implementation/form.html',context)

ukl/views/dm_ukl_v.py
from django.shortcuts import render,redirect, get_object_or_404,HttpResponse
from django.contrib import messages
from funsionariu.models import Funsionariu,UserFunsionariu
from ukl.models import *
from ukl.utils import *
from django.contrib.auth.models import User,Group
from custom.utils import *
from custom.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from users.decorators import allowed_users

# Create your views here.
@login_required
@allowed_users(allowed_roles=['dir_mun'])
def UKLDMDash(request):
	group = request.user.groups.all()[0].name
	diretor = c_user_fun(request.user)
	objects = SurveyUKL.objects.filter(is_sent=True, is_approved=True,municipality__id=diretor.areamunicipality.id).all()
	objects1 = ImplementasaunUKL.objects.filter(survey__municipality__id=diretor.areamunicipality.id).all()
	context = {
		"title":"Dashboard Programa UKL Aprovadu",
		"active_programa":"active",
		"page":"dash",
		"group":group,
		"objects":objects,
		"objects1":objects1,
	}
	return render(request, "dm_ukl/dash.html",context)

@login_required
@allowed_users(allowed_roles=['dir_mun','admpost'])
def DMUKLImplementBenefDetail(request,hashid):
	group = request.user.groups.all()[0].name
	diretor = c_user_fun(request.user)
	# objects = SurveyUKL.objects.filter(is_sent=True, is_approved=True,municipality__id=diretor.areamunicipality.id).all()
	objects = ImplementasaunUKL.objects.get(hashed=hashid)
	implementationImage = ImplementasaunUKLImage.objects.filter(implementasaun=objects)
	context = {
		"title":f"Detallu Implementasaun Programa UKL ba Benefisiariu {objects.benefisiariu.naran}",
		"active_programa":"active",
		"page":"dash",
		"group":group,
		"objects":objects,"implementationImage":implementationImage,
	}
	return render(request, "implementation/detail.html",context)

ukl/templates/implementation/form.html
{% extends "main/layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% if page == "dmimpleform" %}
    <section>
        <div class="container mt-3 p-3">
            <header> 
                <ol class="breadcrumb mb-1 mt-1">
                  <li class="breadcrumb-item"><a href="{% url 'home' %}">Varanda</a></li>
                  {% if page == "form" %}
                  <li class="breadcrumb-item"><a href="{% url 'notifDetailSurveyUKL' benefisiariu.survey.hashed %}">Detallu Survey</a></li>
                  {% endif %}
                  <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
                </ol>
            </header>
            {% if messages %}
                {% for message in messages %} 
                    <div class="alert alert-{{ message.tags }} alert-dismissable">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="card shadow-lg pt-1 rounded" style="border-top: 3px solid #bb0303;">
                        <div class="card-header">{{ legend|upper }}</div>
                        <div class="card-body">
                                {% csrf_token %}
                                {% crispy form %}
                        </div> <!--end card-body-->
                    </div> <!--end card-->
                </div> <!--end col-->
            </div> <!--end row-->
        </div>
    </section>
{% elif page == "form" %}
    <section>
        <div class="container mt-3 p-3">
            <header> 
                <ol class="breadcrumb mb-1 mt-1">
                  <li class="breadcrumb-item"><a href="{% url 'home' %}">Varanda</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'ukl-dash' %}">Dashboard UKL</a></li>
                  <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
                </ol>
            </header>
            {% if messages %}
                {% for message in messages %} 
                    <div class="alert alert-{{ message.tags }} alert-dismissable">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="card shadow-lg pt-1 rounded" style="border-top: 3px solid #bb0303;">
                        <div class="card-header">{{ legend|upper }}</div>
                        <div class="card-body">
                                {% csrf_token %}
                                {% crispy form %}
                        </div> <!--end card-body-->
                    </div> <!--end card-->
                </div> <!--end col-->
            </div> <!--end row-->
        </div>
    </section>
{% elif page == "impleimageform" %}
    <section>
        <div class="container mt-3 p-3">
            <header> 
                <ol class="breadcrumb mb-1 mt-1">
                  <li class="breadcrumb-item"><a href="{% url 'home' %}">Varanda</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'DMUKLImplementBenefDetail' objects.hashed %}">Detallu Implementasaun UKL</a></li>
                  <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
                </ol>
            </header>
            {% if messages %}
                {% for message in messages %} 
                    <div class="alert alert-{{ message.tags }} alert-dismissable">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="card shadow-lg pt-1 rounded" style="border-top: 3px solid #bb0303;">
                        <div class="card-header">{{ legend|upper }}</div>
                        <div class="card-body">
                                {% csrf_token %}
                                {% crispy form %}
                        </div> <!--end card-body-->
                    </div> <!--end card-->
                </div> <!--end col-->
            </div> <!--end row-->
        </div>
    </section>
{%endif%}
<script src="{% static 'main/js/jquery.min.js'%}"> </script>
<script type="text/javascript">
    
    $("#id_municipality").change(function () {
      var municipalityId = $(this).val();
      $.ajax({
        url: "{% url 'ajax_load_posts' %}",
        data: {
          'municipality': municipalityId
        },
        success: function (data) {
          $("#id_administrativepost").html(data);
        }

      });
    });
    $("#id_administrativepost").change(function () {
      var postId = $(this).val();
      $.ajax({
        url: "{% url 'ajax_load_villages' %}",
        data: {
          'post': postId
        },
        success: function (data) {
          $("#id_village").html(data);
        }
      });

    });
    $("#id_village").change(function () {
      var villageId = $(this).val();
      $.ajax({
        url: "{% url 'ajax_load_aldeia' %}",
        data: {
          'village': villageId
        },
        success: function (data) {
          $("#id_aldeia").html(data);
        }
      });

    });
    //load Imagen
    function myFunction() {
      var image = document.getElementById("output");
      image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>
<script>
  var $j = jQuery.noConflict();
  $j("#id_benefisiariu").change(function () {
    var benId = $j(this).val();
    $j.ajax({
      url: "{% url 'ajax_load_detail_benefisiariu' %}",
      data: {
        'benId': benId,
      },
      success: function (data) {
        $j("#DetailBenefisiariu").html(data);
      }
    });

  });
  
</script>
{% endblock %}
{% block scripts %}

{% endblock %}

ukl/templates/implementation/imageRemoveModal.html
<!-- Modal -->
<div class="modal fade" id="removeImage{{ obj.id }}" tabindex="-1" role="dialog" aria-labelledby="removeGalleryLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-success">
        <h5 class="modal-title text-white" id="removeGalleryLabel">Hapaga Imajen</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Ita iha serteja hodi hapaga imajen nee?</p>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Lae</button>
        <a class="btn btn-danger" href="{% url 'deleteImplementationImage' obj.hashed %}">Sim</a>
      </div>
    </div>
  </div>
</div>