aasm_pnds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('summernote/', include('django_summernote.urls')),
    path('', include('main.urls')),
    path('custom/', include('custom.urls')),
    path('users/', include('users.urls')),
    path('funsionariu/', include('funsionariu.urls')),
    path('ukl/', include('ukl.urls')),
    path('notification/', include('notification.urls')),
    path('api/notification/', include('notification.api.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "PNDS - UKL MONITORING SYSTEM - SUPER USER"
admin.site.site_title = "PNDS - UKL MONITORING SYSTEM - SUPER USER"
admin.site.index_title = "Portal Super User"

funsionariu/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('lista-Funsionariu/',views.ListaFunsionariu,name="ListaFunsionariu"),
	path('adisiona-Funsionariu/',views.AddFunsionariu,name="AddFunsionariu"),
	path('altera-dadus-Funsionariu/<str:hashid>',views.UpdateFunsionariu,name="UpdateFunsionariu"),
	
	path('ajax_load_work_area/',views.ajax_load_work_area,name="ajax_load_work_area"),
]

ukl/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dash/', views.UKLDash, name="ukl-dash"),
    
    # survey
    path('survey/add', views.AddSurveyUKL, name="AddSurveyUKL"),
    path('survey/update/<str:hashid>', views.UpdateSurveyUKL, name="UpdateSurveyUKL"),
    path('survey/detail/<str:hashid>', views.DetailSurveyUKL, name="DetailSurveyUKL"),
    path('survey/sent/<str:hashid>', views.SentSurvey, name="SentSurvey"),
    # survey image
    path('survey/image/upload/<str:hashid>', views.AddSurveyImage, name="AddSurveyImage"),
    path('survey/image/update/<str:hashid>', views.UpdateSurveyImage, name="UpdateSurveyImage"),
    path('survey/image/delete/<str:hashid>', views.DeleteSurveyImage, name="DeleteSurveyImage"),

    # survey benefisiariu
    path('survey/benefisiariu/add/<str:hashid>', views.AddBenefisiariu, name="AddBenefisiariu"),
    path('survey/benefisiariu/update/<str:hashid>', views.UpdateBenefisiariu, name="UpdateBenefisiariu"),
    path('survey/benefisiariu/upload/doc/<str:hashid>', views.UploadBenefisiariuDoc, name="UploadBenefisiariuDoc"),
    path('survey/benefisiariu/update/doc/<str:hashid>', views.UpdateBenefisiariuDoc, name="UpdateBenefisiariuDoc"),
    path('survey/benefisiariu/delete/doc/<str:hashid>', views.DeleteBenefisiariuDoc, name="DeleteBenefisiariuDoc"),

    # atualiza info implementasaun
    path('implementation/benefisiariu/info/update/<str:hashid>', views.FPAtualizaInfoImple, name="FPAtualizaInfoImple"),
    path('implementation/benefisiariu/doc/add/<str:hashid>', views.AddImplementationImage, name="AddImplementationImage"),
    path('implementation/benefisiariu/doc/update/<str:hashid>', views.UpdateImplementationImage, name="UpdateImplementationImage"),
    path('implementation/benefisiariu/doc/delete/<str:hashid>', views.deleteImplementationImage, name="deleteImplementationImage"),
    path('implementation/benefisiariu/implementation/info/sent/<str:hashid>', views.SentImplementation, name="SentImplementation"),

    # implementation benefisiariu
    path('implementation/add', views.AddImplementationUKL, name="AddImplementationUKL"),

    # loading
    path('load/benefisiariu/detail', views.ajax_load_detail_benefisiariu, name="ajax_load_detail_benefisiariu"),

    # dir munisipiu
    path('dir/mun/dash/', views.UKLDMDash, name="dirmun-ukl-dash"),
    path('dir/mun/implementation/benefisiariu/<str:hashid>', views.DMUKLImplementBenef, name="implementa-ukl-benef"),
    path('dir/mun/implementation/benefisiariu/detail/<str:hashid>', views.DMUKLImplementBenefDetail, name="DMUKLImplementBenefDetail"),


]

funsionariu/models.py
from django.db import models
from custom.models import *
from django.contrib.auth.models import User


# Create your models here.
class Pozisaun(models.Model):
	naran = models.CharField(max_length=100,null=True)
	def __str__(self):
		template = '{0.naran}'
		return template.format(self)

class Funsionariu(models.Model):
	naran = models.CharField(max_length=200, null=True)
	seksu = models.CharField(choices=[('Mane','Mane'),('Feto','Feto')],max_length=10,null=True,blank=True)
	pozisaun = models.ForeignKey(Pozisaun, null=True,on_delete=models.CASCADE)
	aldeia = models.ForeignKey(Aldeia, on_delete=models.CASCADE,null=True,blank=True)
	village = models.ForeignKey(Village, on_delete=models.CASCADE,null=True,related_name="Village")
	administrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True,related_name="AdministrativePost")
	municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True,related_name="Municipality")
	areamunicipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True,related_name="AreaMunicipality",blank=True,verbose_name="Area Servisu (Munisipiu)")
	areaadministrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True,related_name="AreaAdministrativePost",blank=True,verbose_name="Area Servisu (Postu)")
	areavillage = models.ForeignKey(Village, on_delete=models.CASCADE,null=True,related_name="AreaVillage",blank=True,verbose_name="Area Servisu (Suku)")
	email = models.CharField(max_length=200, null=True)
	nu_telefone = models.CharField(max_length=200, null=True)
	is_active = models.BooleanField(default=True, null=True, blank=True)
	is_nac = models.BooleanField(default=False, null=True, blank=True)
	is_mun = models.BooleanField(default=False, null=True, blank=True)
	is_post = models.BooleanField(default=False, null=True, blank=True)
	image = models.ImageField(upload_to='funsionariu', null=True,blank=True)
	tipu_f = models.CharField(choices=[('Diretor Nacional','Diretor Nacional'),('Diretor Municipio','Diretor Municipio'),('Funcionario Posto','Funcionario Posto'),('Funcionario EIP','Funcionario EIP')],max_length=30,null=True,blank=True)
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)


	def __str__(self):
		template = '{0.naran} {0.pozisaun}'
		return template.format(self)

class UserFunsionariu(models.Model):
	user =  models.OneToOneField(User, on_delete=models.CASCADE,null=True,related_name="userFunsionariu")
	funsionariu = models.OneToOneField(Funsionariu,on_delete=models.CASCADE,related_name="userFunsionariu")
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	user_created =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	hashed = models.CharField(max_length=32, null=True, blank=True)
	def __str__(self):
		template = '{0.funsionariu} {0.user}'
		return template.format(self)	

funsionariu/views.py
from django.shortcuts import render,redirect, get_object_or_404,HttpResponse
from django.contrib import messages
from funsionariu.models import Funsionariu,UserFunsionariu
from .forms import FunsionariuForm,UpdateFunsionariuForm
from django.contrib.auth.models import User,Group
from custom.utils import *
from custom.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from users.decorators import allowed_users

# Create your views here.
@login_required
@allowed_users(allowed_roles=['admin'])
def ListaFunsionariu(request):
	listaFunsionariu = Funsionariu.objects.all()
	context = {
		"title":"Lista Funsionariu PNDS",
		"active_funsionariu":"active",
		"page":"list",
		"listaFunsionariu":listaFunsionariu,
	}
	return render(request, "ListaFunsionariu.html",context)

@login_required
@allowed_users(allowed_roles=['admin'])
def AddFunsionariu(request):
	if request.method == "POST":
		_, newid = getlastid(Funsionariu)
		hashid = hash_md5(str(newid))
		newid2 = getjustnewid(UserFunsionariu)
		hashid2 = hash_md5(str(newid2))
		newid3 = getjustnewid(User)
		form = FunsionariuForm(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.hashed = hashid
			instance.user_created = request.user
			if instance.tipu_f == "Diretor Nacional":
				instance.is_nac = True
				username = str("dn")+str("pnds")+str(newid)  
				group_user = Group.objects.get(name='dir_nac')
			elif instance.tipu_f == "Diretor Municipio":
				instance.is_mun = True
				mun = get_object_or_404(Municipality,id=request.POST.get('areamunicipality'))
				instance.areamunicipality = mun
				username = str("dm")+str(mun.name)+str(newid)  
				group_user = Group.objects.get(name='dir_mun')
			elif instance.tipu_f == "Funcionario Posto":
				instance.is_post = True
				mun = get_object_or_404(Municipality,id=request.POST.get('areamunicipality'))
				post = get_object_or_404(AdministrativePost,id=request.POST.get('areaadministrativepost'))
				instance.areamunicipality = mun
				instance.areaadministrativepost = post
				username = str("fp")+str(post.name)+str(newid)  
				group_user = Group.objects.get(name='admpost')
			instance.save()
			password = make_password('password')
			obj2 = User(id=newid3, username=username, password=password)  
			obj2.save()
			obj3 = UserFunsionariu.objects.create(user=obj2,funsionariu=instance,user_created=request.user,hashed=hashid2)
			user = User.objects.get(pk=newid3)
			user.groups.add(group_user)
			messages.success(request, f'Funsionariu Foun Rejistu ho Susesu.')
			return redirect('ListaFunsionariu')
	else:	
		form = FunsionariuForm()
	context ={
		"title":"Formulariu Rejistu Funsionariu",
		"page":"form",
		"form":form,
		"active_funsionariu":"active",
	}
	return render(request,'ListaFunsionariu.html',context)

@login_required
@allowed_users(allowed_roles=['admin'])
def ajax_load_work_area(request):
	tipu_f = request.GET.get('tipu_f')
	if tipu_f == "Diretor Nacional":
		page = "dn"
		mun = None
	elif tipu_f == "Diretor Municipio":
		page = "dm"
		mun = Municipality.objects.all()
	elif tipu_f == "Funcionario Posto":
		page = "fp"
		mun = Municipality.objects.all()
	return render(request, 'loadWorkArea.html', {'mun': mun,'page': page})

@login_required
@allowed_users(allowed_roles=['admin'])
def UpdateFunsionariu(request,hashid):
	funsionariu = get_object_or_404(Funsionariu,hashed=hashid)
	if request.method == "POST":
		newid2 = getjustnewid(UserFunsionariu)
		hashid2 = hash_md5(str(newid2))
		newid3 = getjustnewid(User)
		form = UpdateFunsionariuForm(request.POST,request.FILES,instance=funsionariu)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request, f'Dadus Funsionariu Altera ho Susesu.')
			return redirect('ListaFunsionariu')
	else:	
		form = UpdateFunsionariuForm(instance=funsionariu)
	context ={
		"title":"Formulariu Altera Dadus Funsionariu",
		"page":"form",
		"form":form,
		"active_funsionariu":"active",
	}
	return render(request,'ListaFunsionariu.html',context)

funsionariu/templates/ListaFunsionariu.html
{% extends "main/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
	<section>
        <div class="container mt-5 border border-danger p-3">
          <!-- Page Header-->
          <header> 
            <ol class="breadcrumb mb-1 mt-1">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">Varanda</a></li>
              {% if page == "form" %}
              <li class="breadcrumb-item"><a href="{% url 'ListaFunsionariu' %}">Lista Funsionariu</a></li>
              {% endif %}
              <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
            </ol>
          </header>
                    {% if messages %}
                        {% for message in messages %} 
                            <div id="divmessage" class="alert alert-{{ message.tags }} alert-dismissable">
                              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                              {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
          {% if page == "list" %}
          <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-header d-flex justify-content-between text-center">
                  <div class="d-flex justify-content-between">
                     <a href="{% url 'AddFunsionariu' %}" class="btn btn-sm btn-info mr-2" title="Add Data"> <i class="fa fa-plus-square"></i> Rejistu Funsionariu</a>
                  </div>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="example"  class="table table-hover table-striped">
                      <thead>
                        <tr>
                          <th>Nu</th>
                          <th class="text-center"><i class="fa fa-user"></i></th>
                          <th>Naran Kompletu</th>
                          <th>Seksu</th>
                          <th>Pozisaun</th>
                          <th>Nu. Kontaktu</th>
                          <th>Email</th>
                          <th class="text-center">Asaun</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for data in listaFunsionariu %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td class="text-center">{% if data.image %}<a href="{{data.image.url}}" target="_blank"><img src="{{data.image.url}}" width="50px" height="50px"></a>{%else%}{%endif%}</td>
                          <td>{{ data.naran }}</td>
                          <td>{{ data.seksu }}</td>
                          <td>{{ data.pozisaun }}</td>
                          <td>{{ data.nu_telefone }}</td>
                          <td>{{ data.email }}</td>
                          <td>
                            <div class="d-flex justify-content-center"> 
                              <div class="flex-fill"><a href="{% url 'home' %}" class="btn btn-sm btn-info" title="Detallu Programa"><i class="fa fa-eye"></i> Detallu</a></div>
                              <div class="flex-fill"><a href="{% url 'UpdateFunsionariu' data.hashed %}" class="btn btn-sm btn-success" title="Altera Programa"><i class="fa fa-pencil"></i> Altera</a></div>
                            </div>  
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {%endif%}
          {% if page == "form" %}
          <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-header d-flex justify-content-between text-center">
                </div>
                <div class="card-body">
                  <script src="{% static 'main/js/jquery.min.js' %}"></script>
                  {% csrf_token %}
                  {% crispy form %}
                </div>
              </div>
            </div>
          </div>
          <script src="{% static 'main/js/jquery.min.js'%}"> </script>
          <script type="text/javascript">
            $("#id_areamunicipality").change(function () {
              var municipalityId = $(this).val();
              $.ajax({
                url: "{% url 'ajax_load_posts' %}",
                data: {
                  'municipality': municipalityId
                },
                success: function (data) {
                  $("#id_areaadministrativepost").html(data);
                }

              });
            });
            $("#id_areaadministrativepost").change(function () {
              var postId = $(this).val();
              $.ajax({
                url: "{% url 'ajax_load_villages' %}",
                data: {
                  'post': postId
                },
                success: function (data) {
                  $("#id_areavillage").html(data);
                }
              });

            });
            $("#id_municipality").change(function () {
              var municipalityId = $(this).val();
              $.ajax({
                url: "{% url 'ajax_load_posts' %}",
                data: {
                  'municipality': municipalityId
                },
                success: function (data) {
                  $("#id_administrativepost").html(data);
                }

              });
            });
            $("#id_administrativepost").change(function () {
              var postId = $(this).val();
              $.ajax({
                url: "{% url 'ajax_load_villages' %}",
                data: {
                  'post': postId
                },
                success: function (data) {
                  $("#id_village").html(data);
                }
              });

            });
            //load Imagen
            function myFunction() {
              var image = document.getElementById("output");
              image.src = URL.createObjectURL(event.target.files[0]);
            }
          	
          </script>
          {%endif%}
        </div>
      </section>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $(document).ready( function () {
        var table = $('#example').removeAttr('width').DataTable( {
            
        });
    } );
</script>
{% endblock %}

funsionariu/templates/loadWorkArea.html
{% load static %}
{% if page == "dn" %}
Nasional
{% elif page == "dm" %}
Area Servisu<br>
	<select required name="areamunicipality" class="form-control my-2">
		<option>-----Hili Munisipiu-----</option>
		{% for i in mun %}
			<option value="{{i.id}}">{{i.name}}</option>
		{% endfor %}
	</select>
{% elif page == "fp" %}
Area Servisu<br>
	<select id="id_areamunicipality" required name="areamunicipality" class="form-control my-2">
		<option>-----Hili Munisipiu-----</option>
		{% for i in mun %}
			<option value="{{i.id}}">{{i.name}}</option>
		{% endfor %}
	</select>
	<select id="id_areaadministrativepost" required name="areaadministrativepost" class="form-control my-2">
		<option>Postu Administrativu</option>
	</select>

<script type="text/javascript">
var $j = jQuery.noConflict();
$j("#id_areamunicipality").change(function () {
  var municipalityId = $j(this).val();
  $j.ajax({
    url: "{% url 'ajax_load_posts' %}",
    data: {
      'municipality': municipalityId
    },
    success: function (data) {
      $j("#id_areaadministrativepost").html(data);
    }

  });
});
$j("#id_areaadministrativepost").change(function () {
  var postId = $j(this).val();
  $j.ajax({
    url: "{% url 'ajax_load_villages' %}",
    data: {
      'post': postId
    },
    success: function (data) {
      $j("#id_areavillage").html(data);
    }
  });

});
{% endif %}